### ISSUE TITLE
Component error: weback - Integration 'weback' not found.

### ISSUE THREAD

**Issue by fuxing-at** [opravdin/weback-hass#25]
Hallo!
I got to add the integration, but after a restart I got the following error:

Logger: homeassistant.setup
Source: custom_components/weback/__init__.py:47
Integration: weback
First occurred: 10:05:20 AM (1 occurrences)
Last logged: 10:05:20 AM

Error during setup of component weback
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 255, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/weback/__init__.py", line 47, in setup
    devices = weback_api.device_list()
  File "/usr/local/lib/python3.9/site-packages/weback_unofficial/client.py", line 75, in device_list
    session = self.get_session()
  File "/usr/local/lib/python3.9/site-packages/weback_unofficial/client.py", line 137, in get_session
    raise Exception(f"Could not authenticate. {weback_data['Fail_Reason']}")
Exception: Could not authenticate. account or password is incorrect

Any Idea?
Thank!!!
JP

**Comment by harryohalloran** [comment]
I'm having the same issue.

**Comment by JR-aaas** [comment]
I'm having the same issue.

**Comment by kornelremete** [comment]
Same for me :(

**Comment by xNiighT** [comment]
If you have the error "Component error: weback - Integration 'weback' not found." try adding this to the file config/custom-components/weback/manifest.json

> "version": "1.0.0",

after "name": "Weback",

so that it looks like:
{
  "domain": "weback",
  "name": "Weback",
  "version": "1.0.0",
  "documentation": "https://www.home-assistant.io/integrations/weback",

**Comment by JR-aaas** [comment]
**xNiightT is the best. It works :-D**

**Comment by danielccm** [comment]
Hell yeah!

> **xNiightT is the best. It works :-D**
