### ISSUE TITLE
Can not authenticate

### ISSUE THREAD

**Issue by sbias** [opravdin/weback-hass#30]
Looks like i have to specify a region as well, but how?

```
2022-05-07 17:21:47 ERROR (MainThread) [homeassistant.setup] Error during setup of component weback
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/weback/__init__.py", line 47, in setup
    devices = weback_api.device_list()
  File "/srv/homeassistant/lib/python3.9/site-packages/weback_unofficial/client.py", line 75, in device_list
    session = self.get_session()
  File "/srv/homeassistant/lib/python3.9/site-packages/weback_unofficial/client.py", line 137, in get_session
    raise Exception(f"Could not authenticate. {weback_data['Fail_Reason']}")
Exception: Could not authenticate. account or password is incorrect

```

**Comment by sbias** [comment]
okey, i think i found the answer but not a solution : https://community.home-assistant.io/t/weback-cloud-integration-testers-and-help-required/186155/112
if this is true: maybe its a good idea to remove it from hacs so nobody waste time nor money?
