### ISSUE TITLE
I am not able to find weback in the integration

### ISSUE THREAD

**Issue by ramrajg** [opravdin/weback-hass#7]
Hi I have installed the weback cloud integration from hacs but now when I try to add the webback in the integration I am not able to find it.
Also can you tell me where to add the username password as I am not able to find the config file

Thanks
RG

**Comment by ramrajg** [comment]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/weback/__init__.py", line 47, in setup
    devices = weback_api.device_list()
  File "/usr/local/lib/python3.8/site-packages/weback_unofficial/client.py", line 75, in device_list
    session = self.get_session()
  File "/usr/local/lib/python3.8/site-packages/weback_unofficial/client.py", line 133, in get_session
    raise Exception(f"Could not authenticate. {weback_data['Fail_Reason']}")
Exception: Could not authenticate. account or password is incorrect

The account user name and password is right 
I have added it to configuration.yaml file

**Comment by pops106** [comment]
If you are using email it needs to look like this;

weback:
    username: +44-email@address.com
    password: yourpassword

**Comment by opravdin** [comment]
Configurate credentials like @pops106 suggested
